services:
  antizapret-vpn:
    extends:
      file: docker-compose.yml
      service: antizapret-vpn
    environment:
      - DNS=adguardhome
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/adguard/conf:/opt/adguardhome/conf
      - ./config/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
