services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    restart: unless-stopped
    privileged: true
    build: .
    ports:
      - 1194:1194/tcp
      - 1194:1194/udp
    # environment:
      # - DNS=1.1.1.1
      # - DNS_RU=77.88.8.8
      # - DOMAIN=example.com
      # - PORT=1194
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keys:/etc/openvpn
      - ./result:/root/antizapret/result
      - ./config/include-hosts-custom.txt:/root/antizapret/config/include-hosts-custom.txt
      - ./config/exclude-hosts-custom.txt:/root/antizapret/config/exclude-hosts-custom.txt
      - ./config/include-ips-custom.txt:/root/antizapret/config/include-ips-custom.txt
      - ./config/exclude-ips-custom.txt:/root/antizapret/config/exclude-ips-custom.txt
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
