services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    hostname: antizapret
    restart: unless-stopped
    privileged: true
    build: .
    environment:
      - DOMAIN
      - PORT
      - DNS
      - DNS_RU
    ports:
      - 1194:1194/tcp
      - 1194:1194/udp
    dns:
      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/keys:/etc/openvpn
      - ./data/temp:/root/antizapret/temp
      - ./data/result:/root/antizapret/result
      - ./data/config:/root/antizapret/config/custom
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
