services:
  antizapret-vpn:
    extends:
      file: docker-compose.yml
      service: antizapret-vpn
    environment:
      - DNS=adguardhome
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - adguardhome-cache:/opt/adguardhome/conf
      - ./config/adguard:/opt/adguardhome/conf
    restart: unless-stopped

volumes:
  adguardhome-cache:
    name: adguardhome-cache
  antizapret-cache:
    external: true
